In [3]:
import numpy as np

In [4]:
numpy.__version__

'1.18.1'

In [7]:
np? # np.

In [8]:
np.array([1, 4, 2, 5, 3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

In [15]:
mynpArray = np.array([range(i, i + 3) for i in [1, 3, 5, 2]])
print(mynpArray)

[[1 2 3]
 [3 4 5]
 [5 6 7]
 [2 3 4]]


In [36]:
print(mynpArray.ndim)
print(mynpArray.shape)
print(mynpArray.size)
print(mynpArray.dtype)
print("itemsize:", mynpArray.itemsize, "bytes")
print("nbytes:", mynpArray.nbytes, "bytes")

2
(4, 3)
12
int64
itemsize: 8 bytes
nbytes: 96 bytes


In [34]:
print(np.zeros(7, dtype=int))
print()
print(np.ones((3, 5), dtype=float))
print()
print(np.full((3, 5), 3.14))

[0 0 0 0 0 0 0]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [40]:
x = np.arange(0, 20, 2, dtype=np.int8)
print(x)
print(x.itemsize)
print(x.nbytes)
print()
print(np.linspace(0, 1, 5, dtype=np.float16))
print()
print(np.random.normal(0, 1, (3, 3)))

[ 0  2  4  6  8 10 12 14 16 18]
1
10

[0.   0.25 0.5  0.75 1.  ]

[[ 1.21902501  0.65856369  0.01148522]
 [ 1.8229586  -0.20338004 -1.10424532]
 [-0.64700306  1.18001685 -0.75418353]]


In [44]:
x = np.arange(7)
print(x)
print(x[:3])
print(x[3:])
print(x[::3])
print(x[::-1])

[0 1 2 3 4 5 6]
[0 1 2]
[3 4 5 6]
[0 3 6]
[6 5 4 3 2 1 0]


In [65]:
x2d = np.random.randint(10, size=(3, 6)) 
print(x2d)

[[4 7 4 6 5 7]
 [7 7 7 6 2 7]
 [4 7 8 6 8 2]]


In [66]:
print(x2d[1:, :3])  #

[[7 7 7]
 [4 7 8]]


In [67]:
x2d_sub_copy = x2d[:2, :2].copy()
print(x2d_sub_copy)

[[4 7]
 [7 7]]


In [68]:
x2d.reshape((6,3))

array([[4, 7, 4],
       [6, 5, 7],
       [7, 7, 7],
       [6, 2, 7],
       [4, 7, 8],
       [6, 8, 2]])

In [70]:
x2d.reshape((9,2))

array([[4, 7],
       [4, 6],
       [5, 7],
       [7, 7],
       [7, 6],
       [2, 7],
       [4, 7],
       [8, 6],
       [8, 2]])

In [73]:
x2d[:, np.newaxis]

array([[[4, 7, 4, 6, 5, 7]],

       [[7, 7, 7, 6, 2, 7]],

       [[4, 7, 8, 6, 8, 2]]])

In [74]:
x2d[np.newaxis, :]

array([[[4, 7, 4, 6, 5, 7],
        [7, 7, 7, 6, 2, 7],
        [4, 7, 8, 6, 8, 2]]])

In [75]:
x2d[np.newaxis]

array([[[4, 7, 4, 6, 5, 7],
        [7, 7, 7, 6, 2, 7],
        [4, 7, 8, 6, 8, 2]]])

### Concatenation

In [76]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [77]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [99]:
x1 = np.array([1, 2, 3])
x2 = np.array([[9, 8, 7],
               [6, 5, 4]])

np.vstack([x1, x2])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [111]:
x1 = np.array([[1, 2],[3, 4],[5, 6]])
print(x1)
x2 = np.array([[9, 8, 7]])
print(x2.reshape(3,1))

np.hstack([x1, x2.reshape(3,1)])

[[1 2]
 [3 4]
 [5 6]]
[[9]
 [8]
 [7]]


array([[1, 2, 9],
       [3, 4, 8],
       [5, 6, 7]])

### Splitting

In [112]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[0 1 2] [3 4] [5 6 7 8 9]


In [113]:
x = np.arange(16).reshape((4, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
upper, lower = np.vsplit(x, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [115]:
left, right = np.hsplit(x, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### Ufuncs

In [119]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [117]:
print(1.0 / x[1:])

[[0.25       0.2        0.16666667 0.14285714]
 [0.125      0.11111111 0.1        0.09090909]
 [0.08333333 0.07692308 0.07142857 0.06666667]]


In [122]:
print(2 ** x)

[[    1     2     4     8]
 [   16    32    64   128]
 [  256   512  1024  2048]
 [ 4096  8192 16384 32768]]


In [123]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [130]:
np.add.reduce(y)

100.0

In [131]:
np.multiply.reduce(y+1)

293601.0

In [132]:
np.add.accumulate(y)

array([  0.,  10.,  30.,  60., 100.])

In [133]:
np.multiply.accumulate(y+1)

array([1.00000e+00, 1.10000e+01, 2.31000e+02, 7.16100e+03, 2.93601e+05])

In [134]:
# outer product
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])